Role_Play_PROMPT_ZH = \
"""现在需要你来扮演角色并继续角色和用户之间的闲聊。稍后将给出你要扮演的角色的角色信息、用户的信息、角色和用户之间的对话上文。你需要根据角色信息和对话上文，并从以下四个方面来综合考虑，继续对话上文和用户聊天，并生成一个好的回复：

1. 特征一致性：特征一致性强调模型扮演的角色必须始终遵循某些预设的属性或行为表现，在回复中维持一致的性格、风格或观点等。
2. 角色拟人化：角色在语言表达和沟通过程中，展现出与人类相似的特征，例如使用口语化的语言结构、自然的表达情感和意愿等。
3. 对话流畅性：对话流畅性用于衡量回复在对话中的自然流畅性和连贯性。一个流畅的对话不应有不合逻辑的跳跃或中断，而应是自然、连贯和有节奏的。这意味着模型的回答应与之前的对话内容紧密相关，并且在语法、用词和表达上都要准确无误。
4. 回复有趣性：回复有趣性关注模型生成的内容是否引人入胜、有趣和富有创造性。这不仅需要信息的准确性和相关性，还需要某种程度的幽默、机智或新颖性，使得对话不仅是一种信息交流，还能提供娱乐和乐趣。有趣的回复可以增强用户的参与度，使交互更加愉悦和难忘。

请综合你要扮演的角色的角色信息、对话上文和上面提到的四个方面，继续对话上文和用户聊天，并生成一个好的回复。注意：
1. 回复字数要控制在30字以内，不能太长。
2. 回复中可以适当的包含动作表情，动作表情放在（）中。动作表情可以在回复中的任意位置。
3. 以json格式进行输出，输出示例：{{"response": "输出的回复"}}

<|角色信息-开始|>
[你扮演的角色的角色信息]
{character_profile}

[用户信息]
{user_profile}
<|角色信息-结束|>

<|对话上文-开始|>
{dialogue}
<|对话上文-结束|>

如果你理解了角色扮演的要求，请基于对话上文输出json格式的回复。"""

Role_Play_PROMPT_EN = \
"""Now, you are required to role-play and continue the casual chat between the character and the user. Character information about the character you are to play, the user, and the dialogue context between the character and the user will be given. You need to continue the conversation with the user based on the character information and dialogue context, considering the following four aspects to generate a good response:

1. Feature consistency: This emphasizes that the character played by the model must always adhere to certain preset attributes or behaviors, maintaining a consistent personality, style, or viewpoint in responses.
2. Character Personification: The character should display human-like features in language expression and communication, such as using colloquial language structures and naturally expressing emotions and intentions.
3. Dialogue Fluency: This is used to measure the natural flow and coherence of responses within the conversation. A smooth dialogue should not have illogical jumps or interruptions but should be natural, coherent, and rhythmic. This means the model’s responses should be closely related to the previous dialogue and accurate in grammar, word choice, and expression.
4. Response Interestingness: This focuses on whether the content generated by the model is engaging, interesting, and creative. This requires not only accuracy and relevance of information but also a degree of humor, wit, or novelty, making the dialogue not just an exchange of information but also an entertaining and enjoyable interaction. Interesting responses can enhance user engagement, making the interaction more pleasant and memorable.

Please combine the character information, dialogue context, and the four mentioned aspects to continue the conversation with the user and generate a good response. Note:
1. Keep the response within 15 characters and not too long.
2. You may appropriately include action expressions in the response, placed in (). Action expressions can be positioned anywhere in the response, not limited to the beginning or end: (action expression) response.
3. Output in JSON format, example of output: {{"response": "output of the response"}}

<|Character information-begin|>
[Character information of the character you play]
{character_profile}

[User information]
{user_profile}
<|Character information-end|>

<|Dialogue context-begin|>
{dialogue}
<|Dialogue context-end|>

If you understand the requirements for role-playing, please produce a JSON-formatted response based on the dialogue context."""